stages:
  - test
  - build

test:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm test

build-linux:
  stage: build
  image: node:20
  before_script:
    - apt-get update -y && apt-get install -y fuse
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist/*.AppImage
    expire_in: 1 week
  only:
    - main
